coredhcp/coredhcp

client/main.go, main.go, plugins/file/plugin.go, plugins/plugin.go, plugins/server_id/plugin.go
Using new import paths instead of old ones
=> Fixed imports with new path

README.md, cmds/client/main.go, cmds/coredhcp/main.go, config/config.go, coredhcp.go, logger/logger.go, plugins/file/plugin.go, plugins/plugin.go, plugins/server_id/plugin.go
Logrus is a structured logging library that supports hooks and customizations. This is the first step to enable custom logging to multiple backends.
=> Switched to logrus

README.md, plugins/example/plugin.go
Added plugin example section to the readme
=> Readme example plugin

.travis.yml, .travis/tests.sh, config/config.go
We don't have tests yet, but let's start by integrating Travis-CI (and start writing tests)
=> Added Travis-CI configuration

cmds/coredhcp/main.go, config/config.go, coredhcp.go
Round one to make the Config interface cleaner
=> Cleaner Config interface

cmds/client/main.go, cmds/coredhcp/config.yml.example, coredhcp.go
The underlying insomniacslk/dhcp library changed interface recently.
This PR to fix the build after that change.
=> Fix build after dhcp library interface change

coredhcp.go, plugins/server_id/plugin.go
To go with https://github.com/insomniacslk/dhcp/pull/253
=> dhcp6: use changed package interface

coredhcp.go
=> Fix after DHCP API change

config/config.go, coredhcp.go
- Allow running v4 server without v6
- Support v4 relay
=> Improved DHCP v4 support

cmds/coredhcp/config.yml.example, config/config.go, coredhcp.go
This has been offloaded to the DHCP library in
https://github.com/insomniacslk/dhcp/pull/278
=> dhcpv6: Joining multicast group offloaded to dhcp library

plugins/file/plugin.go
=> plugins/file: better logging

.travis.yml, .travis/linters.sh, .travis/tests.sh, cmds/coredhcp/main.go, plugins/file/plugin.go, plugins/plugin.go
=> CI: linters and fixes

coredhcp.go
=> Handle rapid-commit requests

coredhcp.go
=> DHCPv6: handle relay-forw requests

plugins/file/plugin.go
=> Added FIXME entries

cmds/coredhcp/main.go, plugins/range/plugin.go
New plugins have been added but not imported in cmds/coredhcp.
=> Added plugin imports in cmds/coredhcp

plugins/range/plugin.go
* removed unused variables
* removed some code duplication
* various errors/logging fixes
=> [plugins/range] Various fixes

coredhcp.go
I noticed responding to relayed messages was broken on dhcpv4 (the response would go to broadcast, because of an `if` that should have been an `else if`
The RFC has this to say about how to select the address to respond to:
>  If the 'giaddr' field in a DHCP message from a client is non-zero,
>  the server sends any return messages to the 'DHCP server' port on the
>  BOOTP relay agent whose address appears in 'giaddr'. If the 'giaddr'
>  field is zero and the 'ciaddr' field is nonzero, then the server
>  unicasts DHCPOFFER and DHCPACK messages to the address in 'ciaddr'.
>  If 'giaddr' is zero and 'ciaddr' is zero, and the broadcast bit is
>  set, then the server broadcasts DHCPOFFER and DHCPACK messages to
>  0xffffffff. If the broadcast bit is not set and 'giaddr' is zero and
> …
=> server4: Fix peer address logic

cmds/client/main.go, cmds/coredhcp/main.go, config/config.go, config/errors.go, coredhcp.go, handler/handler.go, logger/logger.go, plugins/dns/plugin.go, plugins/dns/plugin_test.go, plugins/example/plugin.go, plugins/file/plugin.go, plugins/netmask/plugin.go, plugins/plugin.go, plugins/range/plugin.go, plugins/router/plugin.go, plugins/server_id/plugin.go, plugins/server_id/plugin_test.go
=> Added license headers

.travis/checklicenses_config.json, .travis/linters.sh
=> [CI] Added license checker

cmds/coredhcp/main.go, go.mod, go.sum, plugins/redis/plugin.go
This is a proposed plugin to get static lease information from redis for review.  Currently only supports IPv4 as I don't have much v6 equipment to test with.
=> Proposed redis plugin

README.md, cmds/coredhcp-generator/README.md, cmds/coredhcp-generator/core-plugins.txt, cmds/coredhcp-generator/main.go
=> [coredhcp-generator] Added README and list of core plugins

plugins/file/plugin.go
=> [plugins/file] better logging

plugins/file/plugin.go
=> File plugin: Use an iaid from a request IANA in the response

cmds/coredhcp-generator/coredhcp.go.template, cmds/coredhcp/main.go
Add -plugins flag for listing compiled in plugins.
eg:
```
./coredhcp -plugins
dns
file
lease_time
nbp
netmask
range
router
server_id
redis
```
=> List plugins

README.md
=> README: update example

cmds/coredhcp/config.yml.example
Follow-up on #105 and #106, this expands the provided example configuration to have more detailed explanations of the various elements that can appear, in particular for various configurations of the "listen" stanza
=> doc: Detail the example configuration

cmds/coredhcp-generator/core-plugins.txt, cmds/coredhcp/config.yml.example, cmds/coredhcp/main.go, plugins/staticroute/plugin.go, plugins/staticroute/plugin_test.go
for configuring one or more classless static routes with DHCP option 121
=> added staticroute plugin

cmds/coredhcp-generator/README.md, cmds/coredhcp-generator/coredhcp.go.template, cmds/coredhcp-generator/main.go, cmds/coredhcp/main.go, logger/logger.go, plugins/file/plugin.go, plugins/file/plugin_test.go
All the calls have been converted to their new equivalent.
=> Replace use of deprecated io/ioutil

.github/workflows/build.yml, .github/workflows/lint.yml
The build artifacts will show up in the artifacts section of the workflow, see https://github.com/actions/upload-artifact?tab=readme-ov-file#where-does-the-upload-go
=> Upload build artifacts
