- plugins/example/plugin.go
Added an example plugin with documentation on how to create a new plugin. I prefer documented sample code to a `plugins/README.md` that may go stale in the future.
> Added example plugin

- cmds/client/main.go
- plugins/server_id/plugin.go
Fix `server_id` plugin and client cmd after changes in the `iana` package of the dhcp library.
> server_id, client: fix build

- plugins/example/plugin.go
This patch updates the example plugin to behave the same for IPv4
as it does for IPv6.
Signed-off-by: Pete Birley <pete@port.direct>
> Updated example plugin to behave the same for IPv4 as IPv6

- cmds/coredhcp/config.yml.example
- config/config.go
- coredhcp.go
- plugins/file/plugin.go
The interface name is necessary to create multicast listeners.
> Config file now requires interface name

- plugins/file/plugin.go
godoc github.com/coredhcp/coredhcp/plugins/file now shows up correctly
> [plugins/file] fix docs

- handler/handler.go
- plugins/file/plugin.go
- plugins/server_id/plugin.go
`return nil, false` in a plugin handler passes a nil dhcp message to the next plugin in the chain, which is almost guaranteed to crash or fail in some other way. The proper way to ignore a valid message (because we don't know what to do with it in this specific plugin) is to return the resp argument unmodified.
I think the documentation of handler was incorrect on this point and possibly misleading, but I'd appreciate if reviewers could double-check that my changes to the doc comment in handler.go make sense ?
Open question: Should maybe MainHandler[46] check for this as well and throw warning/errors/abort processing when receiving `nil, false` ? I can easily add that; but maybe a test or some sort of linter rule is better than checking at runtime
> Stop returning `nil, false` in plugins

- plugins/file/plugin.go
The plugin currently stops when when an entry is found. This does not
let the following plugins to run, and it makes no sense.
> [plugins/file] do not stop when an entry is found

- .travis.yml
Currently, go.mod is ineffective in travis since the default value is GO111MODULE=auto and travis runs go builds in GOPATH, making the auto value translate to off. For example there was a breaking change in the upstream dhcp library that we didn't take in yet, but it's breaking builds anyway
This enables modules unconditionally, as well as go 1.13 which has been released, and removes go 1.11 because our go.mod states go 1.12 as minimum version
> travis: Enable go modules support

- cmds/coredhcp/main.go
- go.mod
- go.sum
- logger/logger.go
This commit adds two flags:
* -logfile, to enable logging to file as additional destination
* -nostdout, to disable logging to stdout
Disabing logging to stdout can help improving QPS in certain setups.
> Add -logfile and -nostdout flags for logging

- coredhcp.go
If the request comes from an ephemeral source port, the server will
reply on such port. However the relay will be listening on server port
instead, so the reply is dropped. With this patch the reply always goes
to the server port if the request is a relay.
> Relay reply

- cmds/coredhcp/main.go
When passed, it will enable debug logging. Currently we don't log
anything at debug level, but since logging proved to be a potential
bottleneck we can move less important messages to debug level.
> Add -debug flag

- coredhcp.go
Reverts coredhcp/coredhcp#67
Copying the relevant portion of the RFC from https://github.com/coredhcp/coredhcp/pull/67#issuecomment-557078623: 
> Relay agents implementing this specification may be configured
instead to 1) use a source port number other than 547 when relaying
messages toward servers and 2) receive responses toward clients on
that same port.
Lower down: 
>Additionally, the IPv6 server MUST check and
use the UDP source port from the UDP packet of the Relay-forward
message in replying to the relay agent.
> Revert "Relay reply"

- cmds/coredhcp/main.go
Not every installation needs the Redis plugin, so we moved it out of
the core plugins, and this patch also stops compiling it by default,
reducing dependencies and binary size of the default cmd.
To compile the redis plugin and other plugins, use
cmds/coredhcp-generator.
> [cmds/contest] Redis plugin is not compiled by default

- .travis.yml
- .travis/setup-integ.sh
This is an extremely WIP PR to demo a setup of network namespaces so we can run real complete client-server exchanges. (cc @insomniacslk)
There is an example test included. It doesn't pass, but it shows that the setup allows communication between client & server: 
`2019/12/05 10:42:18 Handling request from [fe80::f461:cbff:feae:a8ee%ens4]:546`
> Setup network namespaces in travis

- cmds/coredhcp/main.go
- plugins/file/plugin.go
- plugins/nbp/nbp.go
The nbp plugin adds support for network boot programs in both v4 and v6
scenarios. In DHCPv6 we support bootfile URL and params, in DHPv4 we
support tftp server and file name.
> [DRAFT] [plugins/nbp] Implemented conditional NBP handling

- go.mod
- go.sum
- plugins/file/plugin.go
https://github.com/insomniacslk/dhcp/pull/347 changed struct
OptIAAddress to use time.Duration for lifetimes. This is a breaking
change and users need to update.
Note that it still compiles without the changes as time.Duration is an
int64, but the values become incorrect (3600 ns rounded as 0s, instead of 3600s)
> plugin/file: Update for breaking changes in insomniacslk/dhcp

- cmds/coredhcp-generator/coredhcp.go.template
- cmds/coredhcp/main.go
And removed -debug flag. Now all the logging levels can be specified
with -loglevel. "none" is a special log level that disables logging
altogether.
Fixes #86 
> Added -loglevel flag

- plugins/serverid/plugin.go
I am not very familiar with net.IP, but copying the first 4 bytes of
a v4 net.IP currently result in 0.0.0.0.
Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>
> serverid: fix v4ServerID copy

- plugins/netmask/plugin.go
- plugins/router/plugin.go
These plugins don't support IPv6. With the new explicit plugin
registration, completely omitting the setup function for ipv6 in that
case is now possible.
> Remove DHCPv6 stub implementations in unsupported plugins

- go.mod
- go.sum
- plugins/dns/plugin.go
- plugins/dns/plugin_test.go
- plugins/file/plugin.go
- plugins/nbp/nbp.go
- plugins/serverid/plugin.go
- plugins/serverid/plugin_test.go
There were many changes in the interfaces with the introduction of the
getters in the upstream library. I've fixed the compilation failures so the code compiles, but not attempted to improve it to use the getters otherwise
> Update dhcp library to latest upstream and use the new getters

- cmds/coredhcp/config.yml.example
- cmds/coredhcp/main.go
- config/config.go
- config/config_test.go
- coredhcp.go
- go.mod
- go.sum
- plugins/plugin.go
- server/handle.go
- server/serve.go
This implements the changes discussed in #52 
There is an additional remaining issue mentioned in https://github.com/coredhcp/coredhcp/issues/52#issuecomment-532621844 where, when listening on a socket that is not bound to an interface, reply packets, especially broadcast or link-local, may be sent on the wrong interface. 
I believe this is fixable as mentioned in the issue, so this is a draft until we decide on a solution (or decide this is fine for the moment and to commit this)
Individual commit messages have more information
> Allow listening on multiple addresses 

- cmds/coredhcp-generator/coredhcp.go.template
- cmds/coredhcp/main.go
- config/config.go
This lets the user specify a configuration file to load, disregarding
the builtin heuristics for locating it
Fixes #93
> config: Allow overriding config location from flags

- plugins/range/plugin.go
If the leases.txt file was not present on the system, coredhcp would
fail to start --
```
level=info msg="DHCPv4: loading plugin `range`" prefix=plugins
level=warning msg="Failed to close file leases.txt: invalid argument" prefix="plugins/range"
level=fatal msg="cannot open lease file leases.txt: open leases.txt: no such file or directory" prefix=main
```
This changes the call to include the O_CREATE flag to create the
leases file if it does not already exist.
Signed-off-by: Brad Beam <brad.beam@b-rad.info>
> fix: Create leases file if it does not exist

- cmds/coredhcp-generator/core-plugins.txt
- cmds/coredhcp/main.go
- go.mod
- plugins/searchdomains/plugin.go
- plugins/searchdomains/plugin_test.go
Add searchdomains plugin to specify a list of default search domains for DHCPv4 and DHCPv6 clients.
> Add domain search list plugin

- plugins/prefix/plugin.go
- plugins/prefix/plugin_test.go
A missing nilcheck caused prefix allocation to panic for requests without hints
> plugins/prefix: Fix a panic with empty hints

- cmds/coredhcp-generator/coredhcp.go.template
- cmds/coredhcp-generator/main.go
- cmds/coredhcp/main.go
- go.mod
- go.sum
Switched `cmd/coredhcp-generator`, and as a consequence also
`cmd/coredhcp`, to `spf13/pflag` instead of the standard `flag`.
`pflag` gives GNU-style flags and supports args before flags, among many
other things.
Also copied `go.mod` and `go.sum` to the destination directory so it can
be built with go modules.
> Switch to pflag

- .github/codecov.yml
Codecov uses the location of files on disk during coverage, which in our action has an additional prefix compared to the path in the repo, making some of the stats in codecov not work.
https://docs.codecov.io/docs/fixing-paths explains how to address that
> ci: Map paths in codecov to paths in the repo

- plugins/allocators/allocator.go
- plugins/allocators/bitmap/bitmap.go
- plugins/allocators/bitmap/bitmap_ipv4.go
- plugins/allocators/bitmap/bitmap_ipv4_test.go
- plugins/range/plugin.go
- plugins/range/storage.go
- plugins/range/storage_test.go
Mixed improvements to overhaul the plugin
* Use the allocator interface to allocate IPs
* Focus on correctness by wrapping a lock for now; we'll improve that
with some more fine-grained concurrency later
* move things related to file storage of leases to a separate source
file and add some minimal sanity-check tests
* Don't open and close the file descriptor on every single packet
> plugins/range: Add some locking and use the allocator interface

- .github/workflows/build.yml
Viper doesn't support running from gopath at all anymore
(https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md#cannot-find-package)
causing the hcl import error we've seen in PRs.
We can actually just init a stub go module here, and let whichever of
our dependencies specify their own needs in their own go.mod files. This
ends up resolving to "latest" for all our dependencies, which is roughly
equivalent to not having modules at all
> ci: Build coredhcp-generator output with modules

- .github/workflows/build.yml
- cmds/coredhcp-generator/core-plugins.txt
- cmds/coredhcp/main.go
- plugins/sleep/plugin.go
The `sleep` plugin introduces a delay in the chain of response to a DHCP
transaction.
> Created sleep plugin

- plugins/netmask/plugin.go
- plugins/netmask/plugin_test.go
While I was testing my coredhcp setup, I misconfigured the netmask plugin which made CoreDHCP panic. I spotted the bug in formatting the error messages and decided to write some tests while at it.
> fixed errors messages and added tests for netmask plugin

- plugins/file/plugin.go
- plugins/file/plugin_test.go
This allows me to maintain my static lease files better and was marked as TODO in the code anyway
> ignore comment lines in file plugin

- go.mod
- go.sum
- plugins/range/plugin.go
- plugins/range/storage.go
- plugins/range/storage_test.go
The range plugin appends every new entry to a text file, without deduplication, and collisions are possible.
Implementing deduplication on a text file is either inefficient or tricky. Detecting collisions is inefficient, no matter if it's done in-memory and then rewriting the entire text file every time, or by parsing the text file every time.
Sqlite3 offers consistency, uniqueness without performance hit, and can enforce more complex constraints.
However using sqlite3 requires using CGo, which has a bunch of issues:
* it complicates cross-compiling
* builds are slower
* deployments are more complicated (no more single binary, not easily at least)
I have been running CoreDHCP with the sqlite3-based range plugin in my home network without issues so far, and no more duplication, nor …
> [plugins/range] use sqlite3 instead of text file

- plugins/range/plugin.go
- plugins/range/storage.go
- plugins/range/storage_test.go
Added the `hostname` field in the sqlite database to simplify debugging.
Example output:
```
$ echo 'select * from leases4;' | sudo sqlite3 leases4.db
98:e8:fa:XX:XX:XX|192.168.1.130|1705666178|nas
...
```
> plugins/range: added hostname field to database

- cmds/client/README.md
There's been a few issues opened by people trying to use `cmds/client` as a general-purpose dhcp client and for DHCPv4. Add a README to hopefully make it clear that this is not part of CoreDHCP but an internal debugging tool
> Add README note to the debugging client

- cmds/coredhcp-generator/coredhcp.go.template
- cmds/coredhcp/main.go
- go.mod
- server/handle.go
- server/serve.go
Fixes #103
Also make `server.Wait` wait for all the listeners to exit, instead of returning when the first one closes, which we couldn't do before because of the spurious errors it would return - this ensures that the server is completely shut down when `server.Wait` returns, instead of potentially still having listeners answering their last requests.
`errors.Join` requires go 1.20, update go.mod accordingly. CI already runs on 1.20 and up only so doesn't need changes
> server: Ignore net.ErrClosed errors when shutting down

- plugins/allocators/ipcalc_test.go
Using the global non-cryptographic rand source is deprecated since go 1.20, so instead we make an explicit local one with a fixed seed for benchmarking
This was failing in CI: https://github.com/coredhcp/coredhcp/actions/runs/9852814374/job/27202061778
> Remove use of deprecated rand.Read

- cmds/coredhcp/config.yml.example
The example was using the extension ".txt" for what actually is a sqlite3 file
> Fixed example: reference to sqlite3 db rather than old txt file
